### ISSUE TITLE
User interface for treatment of Chromium VI

### ISSUE THREAD

**Issue by nhternup** [foundation-for-environmental-monitoring/IITK-CrVI#1]
Two methods of treating Chromium VI: Iron Sulfate tablets & Electro coagulation.

1. **Output water**:  run test and display result
1. **Input water**:  user selects type of treatment

   1. **Iron Sulfate tablets**: 1 or 2 tablets to be added to the sample (admin / user settable)
The weight of FeSO4.7H2O salt in one tablet is 200 mg. It can treat 6 L of water contaminated with 2 mg/L of Cr(VI). So if it is about 2 mg/l, you need 2 tablets.

   1. **Electrocoagulation**: electrodes to be dipped for min amount of time (admin / user settable)
For electrocoagulation, a current of 40 mA needs 2 h to treat 6 L of water contaminated with 2 mg/L of Cr(VI).

   For input water display result and recommendation after running the test

**Comment by nhternup** [comment]
![ui](https://user-images.githubusercontent.com/4124856/71941806-105aa500-31e1-11ea-9c65-62e7a470e507.png)

**Comment by nhternup** [comment]
![ui](https://user-images.githubusercontent.com/4124856/73233655-2be81880-41ad-11ea-968c-013d0c8389e9.png)

**Comment by Tathagata95** [comment]
It will be good if the app directly tells the user how much weight of FeSO4 or what treatment time for electrocoagulation will be needed. Say,
         Input water: 5 mg/L of Cr(VI)
         Option 1: Add x mg of FeSO4 salt (chemical coagulation)
         Option 2: Allow treatment time of y hours with z mA of current

**Comment by nhternup** [comment]
![ui4](https://user-images.githubusercontent.com/4124856/73791858-21d7a280-47c9-11ea-9d7e-0c874b6b0c37.png)
